sudo: false
os:
  - linux
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-sdk-team
    packages:
    - build-essential
    - libdb++-dev
    - libboost1.55-all-dev
    - autoconf
    - libssl-dev
    - libprotobuf-dev
    - protobuf-compiler
    - libqrencode-dev
    - libtool
    - libminiupnpc-dev
before_install:
  - chmod 755 src/leveldb/build_detect_platform
  - cd src/secp256k1
  - chmod 755 *
  - mkdir build-aux
  - mkdir build-aux/m4
  - ./autogen.sh
  - ./configure --prefix=$HOME/secp256k1
  - make
  - make install
  - cd ../..
script: 
  - cd src
  - make -f makefile.unix
